services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    networks:
      - network
    depends_on:
      - db
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:9OFGsDoUMmAlz4y+m7AvBZ+VedUlfzFAzm/bGLWMdzE=
      APP_DEBUG: true
      APP_TIMEZONE: UTC
      APP_URL: http://localhost
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      APP_MAINTENANCE_DRIVER: file
      APP_MAINTENANCE_STORE: database
      BCRYPT_ROUNDS: "12"
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: s3
      QUEUE_CONNECTION: database
      CACHE_STORE: database
      CACHE_PREFIX: null
      MEMCACHED_HOST: 127.0.0.1
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_MAILER: log
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: "2525"
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: "${APP_NAME}"
      AWS_ACCESS_KEY_ID: 5DqyXgLJUtQ8vKjGvFjg
      AWS_SECRET_ACCESS_KEY: 11xncmmOsiDBEggvtHmAli9EG7BItBTvqH0Y4V6r
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: attachment
      AWS_USE_PATH_STYLE_ENDPOINT: true
      AWS_ENDPOINT: http://minio:9000
      VITE_APP_NAME: "${APP_NAME}"
      JWT_SECRET: cpvWsHpDzKTZX4uORYy0BRA70cBsknzz40V2FJoXSy9CDac7GesI1yfCFOSiLEYG

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network
    volumes:
      - './data/mysql8:/var/lib/mysql'
      
  minio:
    image: docker.io/bitnami/minio:2023
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - network
    volumes:
      - ./data/minio_data:/data

networks:
  network:
    driver: bridge
