services:     
  minio:
    image: docker.io/bitnami/minio:2023
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - network
    volumes:
      - ./data/minio_data:/data

networks:
  network:
    driver: bridge
